/**
 * Radar — detects commercially/consumer-relevant EVENTS from data this
 * project already has, rather than presenting static products (project
 * brief, 2026-09-07). Deliberately pure, query-free functions: the DB
 * assembly lives in lib/queries/radar-events.ts, which is what decides
 * whether to persist anything — this file never touches Prisma.
 *
 * WHY NO NEW `RadarEvent` TABLE (yet): every event type below is fully
 * derivable at query time from MerchantListingSignal's accumulated
 * snapshots (each script run — scripts/ml-enrich-offers.ts,
 * scripts/shopee-first-cycle.ts — appends a new, timestamped signal row
 * rather than overwriting) and AffiliateLinkRegistry. At today's real
 * volume (18 ML catalog products, ~180 real offers, 12 Shopee listings)
 * query-time derivation is fast and correct, and nothing here needs
 * dedup/lifecycle/publication state that only a persisted row could give —
 * see lib/queries/radar-events.ts's doc comment for exactly what would
 * change that calculus (and when to revisit this decision).
 *
 * Every detector requires real evidence for its specific claim — no
 * detector ever fires from "not enough data", it just returns null.
 */

export type RadarEventType =
  | "PRICE_DROP"
  | "TREND_ENTRY"
  | "BESTSELLER_ENTRY"
  | "HIGH_QUALITY_OFFER"
  | "AFFILIATE_LINK_ACTIVATED";

export interface RadarEvidence {
  // Only the fields relevant to the specific event type are populated —
  // never fabricated placeholders for the rest.
  previousPrice?: number;
  currentPrice?: number;
  dropPercent?: number;
  rank?: number;
  offerQualityScore?: number;
  sellerReputationLevel?: string | null;
  freeShipping?: boolean | null;
  condition?: string | null;
  rating?: number | null;
}

export interface RadarEvent {
  type: RadarEventType;
  merchantListingId: string;
  occurredAt: Date;
  evidence: RadarEvidence;
  /** Deterministic, evidence-only copy — see buildEventCopy(). Never
   * generated by an LLM, never promotional filler. */
  headline: string;
}

// ---------------------------------------------------------------------
// Detectors — each takes only the real signals needed for its own claim.
// ---------------------------------------------------------------------

/** A drop below this fraction is noise (rounding, currency formatting
 * quirks) — not a real "price dropped" event. Documented, not hidden. */
export const MIN_PRICE_DROP_FRACTION = 0.03; // 3%

/**
 * Requires two REAL, distinct-priced observations of the same
 * listing (oldest → newest by observedAt) — never fabricates a "previous
 * price" from a single snapshot. Returns null when there's no real drop
 * (price steady or went up) or not enough history yet.
 */
export function detectPriceDrop(
  merchantListingId: string,
  priceHistory: Array<{ price: number; observedAt: Date }>,
): RadarEvent | null {
  if (priceHistory.length < 2) return null;
  const sorted = [...priceHistory].sort((a, b) => a.observedAt.getTime() - b.observedAt.getTime());
  const previous = sorted[sorted.length - 2]!;
  const current = sorted[sorted.length - 1]!;
  if (previous.price <= 0 || current.price >= previous.price) return null;

  const dropPercent = (previous.price - current.price) / previous.price;
  if (dropPercent < MIN_PRICE_DROP_FRACTION) return null;

  return {
    type: "PRICE_DROP",
    merchantListingId,
    occurredAt: current.observedAt,
    evidence: { previousPrice: previous.price, currentPrice: current.price, dropPercent },
    headline: `Preço caiu ${Math.round(dropPercent * 100)}% — de ${formatBRL(previous.price)} para ${formatBRL(current.price)}`,
  };
}

/** Real Mercado Livre bestseller/trend rank <= this counts as "entrou
 * entre os mais procurados" — documented threshold, not a guess dressed
 * up as intelligence. */
export const TOP_RANK_THRESHOLD = 10;

export function detectRankEvent(
  merchantListingId: string,
  input: { bestsellerRank: number | null; trendRank: number | null; observedAt: Date },
): RadarEvent | null {
  const rank = input.bestsellerRank ?? input.trendRank;
  if (rank === null || rank > TOP_RANK_THRESHOLD) return null;
  const type: RadarEventType = input.bestsellerRank !== null ? "BESTSELLER_ENTRY" : "TREND_ENTRY";
  return {
    type,
    merchantListingId,
    occurredAt: input.observedAt,
    evidence: { rank },
    headline:
      type === "BESTSELLER_ENTRY"
        ? `Está entre os mais vendidos (posição #${rank})`
        : `Está entre os mais procurados (posição #${rank})`,
  };
}

/** A real offerQualityScore (lib/services/ml-offer-quality.ts) at or above
 * this, OR a real rating at or above 4.5 (Shopee, where no offer-quality
 * formula exists) — both real, evidence-backed thresholds, never a
 * fabricated "boa oferta" claim. */
export const HIGH_QUALITY_OFFER_SCORE_THRESHOLD = 80;
export const HIGH_QUALITY_RATING_THRESHOLD = 4.5;

export function detectHighQualityOffer(
  merchantListingId: string,
  input: {
    offerQualityScore?: number;
    rating?: number | null;
    sellerReputationLevel?: string | null;
    freeShipping?: boolean | null;
    condition?: string | null;
    observedAt: Date;
  },
): RadarEvent | null {
  const qualifiesByScore =
    input.offerQualityScore !== undefined && input.offerQualityScore >= HIGH_QUALITY_OFFER_SCORE_THRESHOLD;
  const qualifiesByRating = (input.rating ?? 0) >= HIGH_QUALITY_RATING_THRESHOLD;
  if (!qualifiesByScore && !qualifiesByRating) return null;

  const reasons: string[] = [];
  if (input.freeShipping) reasons.push("frete grátis");
  if (input.sellerReputationLevel === "5_green") reasons.push("vendedor bem avaliado");
  if (input.rating && input.rating >= HIGH_QUALITY_RATING_THRESHOLD) reasons.push(`nota ${input.rating.toFixed(1)}`);
  const reasonText = reasons.length > 0 ? ` — ${reasons.join(", ")}` : "";

  return {
    type: "HIGH_QUALITY_OFFER",
    merchantListingId,
    occurredAt: input.observedAt,
    evidence: {
      offerQualityScore: input.offerQualityScore,
      rating: input.rating,
      sellerReputationLevel: input.sellerReputationLevel,
      freeShipping: input.freeShipping,
      condition: input.condition,
    },
    headline: `Oferta forte${reasonText}`,
  };
}

/** Internal/business fact, not a consumer-quality claim — never rendered
 * as if it meant "this is a good deal" (project brief section 5.D). */
export function detectAffiliateLinkActivated(
  merchantListingId: string,
  input: { activatedAt: Date; recentWindowMs?: number },
): RadarEvent | null {
  const windowMs = input.recentWindowMs ?? 7 * 24 * 60 * 60 * 1000; // 7 days
  if (Date.now() - input.activatedAt.getTime() > windowMs) return null;
  return {
    type: "AFFILIATE_LINK_ACTIVATED",
    merchantListingId,
    occurredAt: input.activatedAt,
    evidence: {},
    headline: "Link afiliado ativado",
  };
}

// ---------------------------------------------------------------------
// Recency decay + priority
// ---------------------------------------------------------------------

/** Linear decay to 0 over 72h — documented, testable, not "sophisticated".
 * An event older than this contributes nothing to priority (still
 * returned by the query layer if asked for, just never ranked near the
 * top). */
export const RADAR_DECAY_WINDOW_MS = 72 * 60 * 60 * 1000; // 72h

export function recencyWeight(occurredAt: Date, now: Date = new Date()): number {
  const ageMs = now.getTime() - occurredAt.getTime();
  if (ageMs <= 0) return 1;
  if (ageMs >= RADAR_DECAY_WINDOW_MS) return 0;
  return 1 - ageMs / RADAR_DECAY_WINDOW_MS;
}

const EVENT_TYPE_BASE_WEIGHT: Record<RadarEventType, number> = {
  PRICE_DROP: 100,
  HIGH_QUALITY_OFFER: 70,
  BESTSELLER_ENTRY: 60,
  TREND_ENTRY: 55,
  AFFILIATE_LINK_ACTIVATED: 40,
};

/**
 * Priority = a fact-driven base (event type + recency + how strong the
 * evidence is for THIS event) plus a small, explicitly bounded commercial
 * tie-breaker (project brief section 6: "quando duas ofertas forem
 * essencialmente equivalentes... a oferta com maior retorno econômico
 * pode ser priorizada" — never enough to override a materially better
 * consumer fact). `monetizationScore` never touches `evidence`/`headline`
 * — it only nudges ordering among otherwise-similar events.
 */
export function calculateRadarPriority(
  event: RadarEvent,
  input: { monetizationScore?: number | null; now?: Date } = {},
): number {
  const base = EVENT_TYPE_BASE_WEIGHT[event.type];
  const recency = recencyWeight(event.occurredAt, input.now);
  const magnitude = eventMagnitude(event);
  // Bounded to at most 10 points — deliberately small relative to the
  // 40-100 point base weights above, so it can only break ties, never
  // promote a weak/stale event over a strong/fresh one.
  const commercialNudge = Math.min(10, ((input.monetizationScore ?? 0) / 100) * 10);
  return base * recency * magnitude + commercialNudge;
}

function eventMagnitude(event: RadarEvent): number {
  switch (event.type) {
    case "PRICE_DROP":
      // A 3% drop counts fully as "an event"; a 50%+ drop is capped at 2x
      // — deliberately not unbounded, so a data glitch (a wildly wrong
      // observed price) can't dominate the whole feed.
      return event.evidence.dropPercent
        ? Math.min(2, 1 + event.evidence.dropPercent)
        : 1;
    case "BESTSELLER_ENTRY":
    case "TREND_ENTRY":
      // Rank 1 counts double; rank 10 (the threshold) counts at 1x.
      return event.evidence.rank ? Math.max(1, 2 - (event.evidence.rank - 1) / 9) : 1;
    default:
      return 1;
  }
}

function formatBRL(value: number): string {
  return value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
}
