import type { NormalizedProduct } from "@/types/commerce";

/**
 * Demo catalog for MockAmazonProvider and the database seed. Clearly
 * fictional ASINs/prices — never treat this as real market data, and never
 * seed it into a production database (see prisma/seed.ts guard).
 */
export const MOCK_CATALOG: NormalizedProduct[] = [
  {
    asin: "B0MOCK0001",
    provider: "AMAZON",
    title: "Fone de Ouvido Bluetooth com Cancelamento de Ruído",
    brand: "SoundPeak",
    description:
      "Fone over-ear sem fio com cancelamento ativo de ruído, até 30 horas de bateria e microfone para chamadas.",
    imageUrl: "https://images.example.com/mock/fone-bluetooth.jpg",
    categoryName: "Eletrônicos",
    specifications: {
      Tipo: "Over-ear",
      Conectividade: "Bluetooth 5.3",
      "Autonomia da bateria": "30 horas",
      "Cancelamento de ruído": "Ativo",
    },
    rating: 4.6,
    reviewCount: 3821,
    offer: {
      price: 349.9,
      currency: "BRL",
      originalPrice: 499.9,
      discountPercentage: 30,
      affiliateUrl: "https://www.amazon.com.br/dp/B0MOCK0001",
      availability: "IN_STOCK",
      observedAt: new Date(),
    },
  },
  {
    asin: "B0MOCK0002",
    provider: "AMAZON",
    title: "Air Fryer Digital 5L Inox",
    brand: "CookMax",
    description:
      "Fritadeira elétrica sem óleo com painel digital, 8 funções pré-programadas e cesto antiaderente de 5 litros.",
    imageUrl: "https://images.example.com/mock/air-fryer.jpg",
    categoryName: "Casa e Cozinha",
    specifications: {
      Capacidade: "5 litros",
      Potência: "1700W",
      Painel: "Digital touch",
      Funções: "8 programas",
    },
    rating: 4.8,
    reviewCount: 12904,
    offer: {
      price: 289.0,
      currency: "BRL",
      originalPrice: 399.0,
      discountPercentage: 28,
      affiliateUrl: "https://www.amazon.com.br/dp/B0MOCK0002",
      availability: "IN_STOCK",
      observedAt: new Date(),
    },
  },
  {
    asin: "B0MOCK0003",
    provider: "AMAZON",
    title: "Smartwatch com Monitor Cardíaco e GPS",
    brand: "FitTrack",
    description:
      "Relógio inteligente com tela AMOLED, GPS integrado, monitor de frequência cardíaca e resistência à água.",
    imageUrl: "https://images.example.com/mock/smartwatch.jpg",
    categoryName: "Eletrônicos",
    specifications: {
      Tela: "AMOLED 1.4 polegadas",
      GPS: "Integrado",
      "Resistência à água": "5 ATM",
    },
    rating: 4.4,
    reviewCount: 1988,
    offer: {
      price: 599.9,
      currency: "BRL",
      originalPrice: 599.9,
      discountPercentage: 0,
      affiliateUrl: "https://www.amazon.com.br/dp/B0MOCK0003",
      availability: "IN_STOCK",
      observedAt: new Date(),
    },
  },
  {
    asin: "B0MOCK0004",
    provider: "AMAZON",
    title: "SSD Externo Portátil 1TB USB-C",
    brand: "DataFlow",
    description:
      "Unidade SSD externa com leitura de até 1050MB/s, corpo em alumínio e compatibilidade com USB-C e USB-A.",
    imageUrl: "https://images.example.com/mock/ssd-externo.jpg",
    categoryName: "Informática",
    specifications: {
      Capacidade: "1TB",
      Interface: "USB-C 3.2",
      "Velocidade de leitura": "1050MB/s",
    },
    rating: 4.7,
    reviewCount: 5602,
    offer: {
      price: 429.0,
      currency: "BRL",
      originalPrice: 599.9,
      discountPercentage: 28,
      affiliateUrl: "https://www.amazon.com.br/dp/B0MOCK0004",
      availability: "IN_STOCK",
      observedAt: new Date(),
    },
  },
  {
    asin: "B0MOCK0005",
    provider: "AMAZON",
    title: "Liquidificador de Alta Rotação 1200W",
    brand: "CookMax",
    description:
      "Liquidificador com copo de vidro de 2L, lâminas em aço inoxidável e 6 velocidades.",
    imageUrl: "https://images.example.com/mock/liquidificador.jpg",
    categoryName: "Casa e Cozinha",
    specifications: {
      Potência: "1200W",
      "Capacidade do copo": "2 litros",
      "Material do copo": "Vidro",
    },
    rating: 4.3,
    reviewCount: 892,
    offer: {
      price: 199.9,
      currency: "BRL",
      originalPrice: 249.9,
      discountPercentage: 20,
      affiliateUrl: "https://www.amazon.com.br/dp/B0MOCK0005",
      availability: "IN_STOCK",
      observedAt: new Date(),
    },
  },
  {
    asin: "B0MOCK0006",
    provider: "AMAZON",
    title: "Escova Secadora Rotativa 3 em 1",
    brand: "BelezaPro",
    description:
      "Escova secadora com tecnologia de íons negativos, 3 bocais intercambiáveis e 2 temperaturas.",
    imageUrl: "https://images.example.com/mock/escova-secadora.jpg",
    categoryName: "Beleza",
    specifications: {
      Potência: "1000W",
      Bocais: "3 tamanhos",
      Tecnologia: "Íons negativos",
    },
    rating: 4.5,
    reviewCount: 2431,
    offer: {
      price: 179.9,
      currency: "BRL",
      originalPrice: 229.9,
      discountPercentage: 22,
      affiliateUrl: "https://www.amazon.com.br/dp/B0MOCK0006",
      availability: "IN_STOCK",
      observedAt: new Date(),
    },
  },
  {
    asin: "B0MOCK0007",
    provider: "AMAZON",
    title: "Tênis de Corrida Leve Respirável",
    brand: "RunFast",
    description:
      "Tênis esportivo com cabedal em malha respirável, entressola em EVA e solado de alta aderência.",
    imageUrl: "https://images.example.com/mock/tenis-corrida.jpg",
    categoryName: "Esporte",
    specifications: {
      Cabedal: "Malha respirável",
      Entressola: "EVA",
      "Uso indicado": "Corrida e caminhada",
    },
    rating: 4.2,
    reviewCount: 674,
    offer: {
      price: 219.9,
      currency: "BRL",
      originalPrice: 219.9,
      discountPercentage: 0,
      affiliateUrl: "https://www.amazon.com.br/dp/B0MOCK0007",
      availability: "IN_STOCK",
      observedAt: new Date(),
    },
  },
  {
    asin: "B0MOCK0008",
    provider: "AMAZON",
    title: "Babá Eletrônica com Câmera Full HD",
    brand: "BabyCare",
    description:
      "Monitor de bebê com câmera Full HD, visão noturna, áudio bidirecional e sensor de temperatura.",
    imageUrl: "https://images.example.com/mock/baba-eletronica.jpg",
    categoryName: "Bebê",
    specifications: {
      Resolução: "Full HD",
      "Visão noturna": "Sim",
      Alcance: "300 metros",
    },
    rating: 4.6,
    reviewCount: 341,
    offer: {
      price: 349.0,
      currency: "BRL",
      originalPrice: 449.0,
      discountPercentage: 22,
      affiliateUrl: "https://www.amazon.com.br/dp/B0MOCK0008",
      availability: "IN_STOCK",
      observedAt: new Date(),
    },
  },
  {
    asin: "B0MOCK0009",
    provider: "AMAZON",
    title: "Cafeteira Elétrica Programável 1,5L",
    brand: "CookMax",
    description:
      "Cafeteira com timer programável, jarra corta-pingos e capacidade para até 15 xícaras.",
    imageUrl: "https://images.example.com/mock/cafeteira.jpg",
    categoryName: "Casa e Cozinha",
    specifications: {
      Capacidade: "1,5 litros",
      Timer: "Programável 24h",
      Filtro: "Permanente",
    },
    rating: 4.1,
    reviewCount: 156,
    offer: {
      price: 159.9,
      currency: "BRL",
      originalPrice: 159.9,
      discountPercentage: 0,
      affiliateUrl: "https://www.amazon.com.br/dp/B0MOCK0009",
      availability: "OUT_OF_STOCK",
      observedAt: new Date(),
    },
  },
  {
    asin: "B0MOCK0010",
    provider: "AMAZON",
    title: "Caixa de Som Bluetooth Portátil à Prova d'Água",
    brand: "SoundPeak",
    description:
      "Caixa de som portátil com certificação IPX7, 12 horas de bateria e graves reforçados.",
    imageUrl: "https://images.example.com/mock/caixa-de-som.jpg",
    categoryName: "Eletrônicos",
    specifications: {
      Potência: "20W RMS",
      Bateria: "12 horas",
      "Resistência à água": "IPX7",
    },
    rating: 4.7,
    reviewCount: 4520,
    offer: {
      price: 149.9,
      currency: "BRL",
      originalPrice: 229.9,
      discountPercentage: 35,
      affiliateUrl: "https://www.amazon.com.br/dp/B0MOCK0010",
      availability: "IN_STOCK",
      observedAt: new Date(),
    },
  },
];
