import { AffiliateDisclosure } from "@/components/affiliate-disclosure";
import type { ShopeeShowcaseItem } from "@/lib/queries/shopee-showcase";

/**
 * Real Shopee opportunities on /ofertas. Server Component — no "use
 * client" (see components/amazon-br-showcase.tsx's incident comment for
 * why that matters: AffiliateDisclosure's import chain touches server-only
 * env config, which would crash hydration if this were client-side).
 *
 * CTA always goes through the internal /go/shopee/[externalId] redirect —
 * never the raw affiliateUrl directly — so every click is tracked via
 * AffiliateClick (project brief rule). This is the one deliberate
 * difference from components/amazon-br-showcase.tsx, whose links are
 * owner-provided Special Links required to stay byte-for-byte unmodified;
 * Shopee's links are generated by us, through our own redirect, by design.
 */
export function ShopeeShowcase({ items }: { items: ShopeeShowcaseItem[] }) {
  if (items.length === 0) return null;

  return (
    <section className="mt-10">
      <h2 className="text-lg font-semibold">Achados na Shopee</h2>
      <p className="text-foreground/70 mt-1 text-sm leading-relaxed">
        Produtos selecionados para você acompanhar e comparar antes de
        comprar.
      </p>
      <div className="mt-2">
        <AffiliateDisclosure />
      </div>
      <div className="mt-5 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {items.map((item) => (
          <article
            key={item.merchantListingId}
            className="border-border-subtle flex h-full flex-col rounded-lg border p-4"
          >
            <span className="text-foreground/50 text-xs font-semibold tracking-wide uppercase">
              Shopee
            </span>
            <h3 className="mt-1 text-sm font-semibold">{item.title}</h3>
            <a
              href={`/go/shopee/${encodeURIComponent(item.externalId)}?pageType=ofertas&pageSlug=ofertas&source=shopee_showcase`}
              target="_blank"
              rel="sponsored nofollow noopener noreferrer"
              className="bg-brand text-brand-foreground mt-4 inline-flex min-h-11 items-center justify-center rounded-full px-5 text-sm font-semibold hover:opacity-90"
            >
              Ver na Shopee
            </a>
          </article>
        ))}
      </div>
    </section>
  );
}
