/**
 * Products the owner pasted from the Mercado Livre affiliate panel
 * ("Perfil de afiliado > Produtos selecionados"), one row per product BLOCK exactly
 * as the panel showed it, repeats included (the owner asked for every pasted block) on the date in `capturedAt`. The panel gives no item
 * id, so a row is identified by its title; the link itself is generated by
 * the owner with the panel's "Compartilhar" button.
 *
 * `extras` marks a temporary "Ganhos extras" campaign: the rate is real today
 * and may expire, so it must be re-checked when the link is generated.
 * `rating` is null when the panel showed none. Add new pastes at the bottom.
 */
export interface PanelPick {
  /** Unique per row: the title, plus " (repetido N)" for the Nth repeat of it. */
  id: string;
  title: string;
  /** Commission shown by the panel, e.g. 0.16. */
  rate: number;
  extras: boolean;
  /** Price the panel showed, in BRL. */
  price: number;
  /** The "+N vendidos" badge, as a number (+10mil -> 10000). */
  sold: number;
  rating: number | null;
  group: string;
  sponsored?: boolean;
  /** Tagged "MAIS BUSCADO" by the panel. */
  searched?: boolean;
  /** Product page address read from the panel card (what the Linkbuilder needs). */
  productUrl?: string;
  capturedAt: string;
}

import { ML_PANEL_URLS } from "@/lib/config/ml-panel-urls";

const D = "2026-09-21";
type Row = [
  string,
  number,
  0 | 1,
  number,
  number,
  number | null,
  string,
  boolean?,
];

// Reset total 2026-09-24 (owner's decision): the list is rebuilt only from a fresh, passive
// read of the panel's Casa, Móveis e Decoração category. The previous list (1012 rows) is in
// git history at commit 6d691d3.
const rows: Row[] = [];

/** Titles the panel tagged "MAIS BUSCADO" (the panel's own search signal). */
const SEARCHED_TITLES = new Set<string>();

const seenTitles = new Map<string, number>();

export const ML_PANEL_PICKS: readonly PanelPick[] = rows.map(
  ([title, pct, extras, price, sold, rating, group, sponsored]) => {
    const n = (seenTitles.get(title) ?? 0) + 1;
    seenTitles.set(title, n);
    return {
      id: n === 1 ? title : `${title} (repetido ${n})`,
      title,
      rate: pct / 100,
      extras: extras === 1,
      price,
      sold,
      rating,
      group,
      ...(sponsored ? { sponsored: true } : {}),
      ...(SEARCHED_TITLES.has(title) ? { searched: true } : {}),
      ...(ML_PANEL_URLS[title] ? { productUrl: ML_PANEL_URLS[title] } : {}),
      capturedAt: D,
    };
  },
);
